create table PRODUCTS
(
    PRODUCT_ID      VARCHAR2(1000) not null
        primary key,
    PRODUCT_NAME    VARCHAR2(1000) not null,
    PRODUCT_DETAILS VARCHAR2(2000) not null,
    ACTUAL_PRICE    NUMBER         not null,
    DISCOUNT        NUMBER         not null,
    SELLING_PRICE   NUMBER         not null,
    STOCK           NUMBER         not null,
    TAGS            VARCHAR2(1000) not null,
    EMAIL           VARCHAR2(1000) not null
        references SELLERS,
    SHORT_DES       VARCHAR2(1000) not null
)
/

INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('lg gram 16z90p-3817', 'LG Gram 16Z90P', 'quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur', 3200, 10, 2880, 55, 'laptop', 'debnatharupbzs@gmail.com', 'm, quis nostrud exercitation ullamco laboris nisi ut');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('amazon basics gaming headset for pc and consoles-4336', 'Amazon Basics Gaming', '"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores ut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil', 2800, 10, 2520, 31, 'accessories', 'debnatharupbzs@gmail.com', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('audio-technica ath-g1wl-3075', 'Audio-Technica ATH-G1WL', 'ore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"', 2000, 10, 1800, 41, 'accessories', 'debnatharupbzs@gmail.com', 'minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliqui');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('amazon essentials men''s regular-fit-930', 'Amazon Essentials Men''s Regular-fit', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur', 2300, 10, 2070, 34, 'men', 'debnatharupbzs@gmail.com', 'minim veniam, quis nostrud exercitation ');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('wrangler authentics men''s classic-1077', 'Wrangler Authentics Men''s Classic', ' natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"', 2300, 43, 1311, 323, 'men', 'debnatharupbzs@gmail.com', 'iam, quis nostrud exercitation ullamco laboris ');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('samsung galaxy s22-1002', 'Samsung Galaxy S22', 'qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur', 23000, 10, 20700, 233, 'phone', 'debnatharupbzs@gmail.com', 'esse cillum dolore eu fugiat nulla pariatur');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('this here flesh-552', 'This Here Flesh', 'perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitatione', 2300, 10, 2070, 243, 'books', 'debnatharupbzs@gmail.com', 'nostrud exercitation ullamco laboris nisi u');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('frito-lay ultimate snack-591', 'Frito-Lay Ultimate Snack', 'nventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem nventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem', 230, 10, 207, 233, 'daily need', 'debnatharupbzs@gmail.com', 'lore eu fugiat nulla pariatur. Excepteur sint');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('gatorade classic thirst-2887', 'Gatorade Classic Thirst', 'tur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur', 2500, 10, 2250, 350, 'daily need', 'debnatharupbzs@gmail.com', 'is nostrud exercitation ullamco laboris nisi ut');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('3-tier metal rolling utility cart-4738', '3-Tier Metal Rolling Utility Cart', 'de omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iu', 2400, 30, 1680, 34, 'daily need', 'debnatharupbzs@gmail.com', 'trud exercitation ullamco laboris');
INSERT INTO C##PURCHASE_POINT.PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DETAILS, ACTUAL_PRICE, DISCOUNT, SELLING_PRICE, STOCK, TAGS, EMAIL, SHORT_DES) VALUES ('real friends-3486', 'Real Friends', 'pernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla', 1200, 20, 960, 434, 'book', 'debnatharupbzs@gmail.com', 'git, sed quia consequuntur magni dolore');