create table NOTIFICATION
(
    NOTIFICATION_TEXT VARCHAR2(3000) not null,
    EMAIL             VARCHAR2(1000) not null
        references USERS,
    "DATE"            DATE           not null
)
/

INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('tfhtfhtr has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-18 23:32:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-18T17:33:02.174Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-18 23:33:02', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ggrttbr r brb trt  has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:17:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-21T19:56:46.795Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:56:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('hgfddtfdg has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 02:07:02', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('dthgft trhtr h has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-18 22:22:09', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('trhhytjhythyt has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 02:06:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order 2022-02-21T22:08:33.284Z has been cancelled', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 09:52:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order 2022-02-21T22:08:33.284Z has been cancelled', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 09:58:08', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order 2022-02-21T21:27:07.689Z has been cancelled', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 09:59:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('trhhytjhythyt has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 10:00:16', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('hgfddtfdg has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 10:00:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('jkmfujfjdyt has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 10:00:23', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-23T04:00:41.316Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 10:00:41', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('nhgfnnhg  tnbtrnhtr has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-18 21:22:06', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-18T15:22:21.123Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-18 21:22:21', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-21T21:27:07.689Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 03:27:07', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('trhhytjhythyt has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 04:04:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('fgfhhgf has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 04:04:48', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('gtrhthh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 04:04:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-21T22:05:07.573Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 04:05:07', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ggrttbr r brb trt  has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 04:07:27', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('fgfhhgf has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 04:07:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-21T22:08:33.284Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 04:08:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Amazon Basics Gaming has been added to your cart!', 'b@gmail.com', TO_DATE('2022-01-23 16:26:22', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ujg jcgwjh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-18 21:19:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('trhhytjhythyt has been added to your wishlist!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-18 21:19:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Amazon Basics Gaming has been added to your wishlist!', 'b@gmail.com', TO_DATE('2022-01-23 16:26:37', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Audio-Technica ATH-G1WL has been added to your cart!', 'b@gmail.com', TO_DATE('2022-01-23 16:26:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-23T10:27:26.958Z', 'b@gmail.com', TO_DATE('2022-01-23 16:27:26', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ujg jcgwjh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 16:18:14', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('fgfhhgf has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 12:40:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('jkmfujfjdyt has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 12:40:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-23T06:40:15.032Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 12:40:15', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order 2022-02-21T22:05:07.573Z has been delivered! Please give review on the puchased products. Thank you!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-23 13:14:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('dfghbf hgdhgbtdh  has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 15:54:16', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ggrttbr r brb trt  has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 15:54:27', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-18T17:12:46.693Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-18 23:12:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-19T11:15:05.256Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:15:05', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ujg jcgwjh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:17:16', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('regbgfbgfbnddgf has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:17:22', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-19T11:18:51.632Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:18:51', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ujg jcgwjh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:20:47', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-19T11:21:28.086Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:21:28', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ujg jcgwjh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:21:36', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-19T11:31:55.694Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:31:55', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('dthgft trhtr h has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:32:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('dfghbf hgdhgbtdh  has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:35:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-19T11:41:34.674Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:41:34', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('trhhytjhythyt has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:50:03', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-19T11:50:40.717Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-19 17:50:40', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('trhhytjhythyt has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:54:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('fgfhhgf has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:54:49', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('nhgfnnhg  tnbtrnhtr has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:54:55', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ggrttbr r brb trt  has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:55:01', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-21T19:55:31.769Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:55:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('ggrttbr r brb trt  has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:55:40', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('hgfddtfdg has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:55:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('fngfhnn nf jytjydtj has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:55:49', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('fgfhhgf has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:55:54', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('fhgdtyh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:56:12', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('fhgdtyh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:57:05', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('gtrhthh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:57:11', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('tfhtfhtr has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:57:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('uyfytgc ujtrhgtrh has been added to your cart!', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:57:50', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO C##PURCHASE_POINT.NOTIFICATION (NOTIFICATION_TEXT, EMAIL, "DATE") VALUES ('Your order has been successfully placed! Order id: 2022-02-21T19:58:12.455Z', 'debnatharupbzs@gmail.com', TO_DATE('2022-01-22 01:58:12', 'YYYY-MM-DD HH24:MI:SS'));